import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Deep Research Archive',
  description: '混合研究法驱动的深度研究报告知识库',
  lang: 'zh-CN',

  head: [
    ['link', { rel: 'icon', href: '/favicon.ico' }],
  ],

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Deep Research',

    nav: [
      { text: '首页', link: '/' },
      { text: '报告', link: '/reports/' },
      { text: '方法论', link: '/guide/methodology' },
    ],

    sidebar: {
      '/reports/': [
        {
          text: '研究报告',
          items: [
            { text: '2026', items: [
              { text: '中国重男轻女观念变迁', link: '/reports/2026/china-son-preference' },
            ]},
          ]
        }
      ],
      '/guide/': [
        {
          text: '指南',
          items: [
            { text: '研究方法论', link: '/guide/methodology' },
          ]
        }
      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/qiao-925/deep-research' }
    ],

    footer: {
      message: '基于对抗性验证流程的深度研究报告',
      copyright: 'Generated by Claude Code Deep Research'
    },

    search: {
      provider: 'local',
      options: {
        translations: {
          button: { buttonText: '搜索文档', buttonAriaLabel: '搜索' },
          modal: {
            noResultsText: '无法找到相关结果',
            resetButtonTitle: '清除查询条件',
            footer: { selectText: '选择', navigateText: '切换', closeText: '关闭' }
          }
        }
      }
    },

    outline: {
      label: '目录',
      level: [2, 3]
    },

    docFooter: {
      prev: '上一篇',
      next: '下一篇'
    },

    lastUpdated: {
      text: '最后更新于',
    },

    editLink: {
      pattern: 'https://github.com/qiao-925/deep-research/edit/main/:path',
      text: '在 GitHub 上编辑此页'
    }
  }
})
